services:
  app:
    build: ./
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks:
      - back
    depends_on:
      - db
      - cache

  db:
    image: postgres
    env_file:
      - ./.env
    restart: always
    networks:
      - back

  cache:
    image: redis
    restart: always
    networks:
      - back
    env_file:
      - ./.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

networks:
  back:
